
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    #network_mode: host
    ports:
      - 9090:9090
    volumes:
      - prometheus-storage:/var/lib/prometheus
      - ./config-scripts:/etc/prometheus/config
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'
    links:
      - switchApi
    depends_on:
      - switchApi
  switchApi:
    image: simpleswitch:latest
    build:
      context: "ApplicationUnderTest/SimpleApi1"
      dockerfile: "Dockerfile"
    ports:
      - "9000:8080"
      - "5001:5001"
    
  pg_grafana:
    container_name: pg_grafana
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: my_grafana_db
      POSTGRES_USER: my_grafana_user
      POSTGRES_PASSWORD: my_grafana_pwd
    ports:
      - "5499:5432"
    volumes:
      - pg_grafana:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: pg_grafana:5432
      GF_DATABASE_NAME: my_grafana_db
      GF_DATABASE_USER: my_grafana_user
      GF_DATABASE_PASSWORD: my_grafana_pwd
      GF_DATABASE_SSL_MODE: disable
    restart: unless-stopped
    depends_on:
        - pg_grafana
    links:
      - prometheus
      - influxdb
    ports:
      - 3111:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  influxdb:
    image: influxdb:1.8
    
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      # - INFLUXDB_HTTP_AUTH_ENABLED=TRUE 
      # - INFLUXDB_ADMIN_USER="admin"
      # - INFLUXDB_ADMIN_PASSWORD="paswoord"
      # - INFLUXDB_WRITE_USER="openhab"
      # - INFLUXDB_WRITE_USER_PASSWORD="paswoord
      # - INFLUXDB_READ_USER="grafana"
      # - INFLUXDB_READ_USER_PASSWORD="paswoord"
  influxdb-ui:
    image: influxdata/influxdb3-ui:1.1.0
    
    ports:
      - "8888:80"
    
  
  k6:
    image: loadimpact/k6:latest
    container_name: k6
    expose:
      - 5665:5665
    depends_on:
      - switchApi
    links:
      - switchApi
      - influxdb
    #environment:
      # k6 only outputs to one destination, so cannot get results in influxdb and see them in the web dashboard at the same time
      # To use the web dashboard, uncomment the line below and comment out the --out influxdb part in the command section
      # - K6_WEB_DASHBOARD=true
    volumes:
      - ./k6scripts:/k6-tests
    entrypoint: [ "k6" ]
    command: [ "run", "/k6-tests/test1.js", "--out", "influxdb=http://influxdb:8086/k6" ]      
volumes:
  pg_grafana:
    driver: local
  grafana:
    driver: local
  pg_data_wh:
    driver: local
  prometheus-storage:
    driver: local
  
