apiVersion: 1

deleteDatasources:
  - name: LOCAL_PROMETHEUS
    orgId: 1

datasources:
  - name: LOCAL_PROMETHEUS
    type: prometheus
    access: proxy
    uid: cevyn8xwabcw0c
    url: http://prometheus:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      pdcInjected: false
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true
